# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Tyler Harkcom
title: B.S. Computer Science, Minor in Engineering Leadership
email: tylerbharkcom@gmail.com
website: linktr.ee/tylerharkcom

# Social links
# twitter_username: facespics
github_username:  tylerharkcom
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: tylerharkcom
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello! My name is Tyler and I'm a senior studying computer science with a minor in engineering leadership at the Univerity of Central Florida. 
  
  I am passionate about technology, collaboration, and leadership, with a love for developing and delivering solutions.
 
  Outside of the classroom I'm involved with the Engineering Leadership and Innovation Institute, UCF's engineering leadership development program, as well as my start-up venture, [Streats: Where Food Meets](https://www.gostreats.com), which aims to revolutionize the way we interact with food trucks. 

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering and leadership some of my other interests and hobbies are:
   - Cooking
   - Sports
   - Music

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
